version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/cosmoteerships.sql:/docker-entrypoint-initdb.d/cosmoteerships.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
#      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: s3
    volumes:
      - "./localstack:/docker-entrypoint-initaws.d"
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
